title: Yunjiao Liu # your name (or website title) here
logo: "/images/IMG45.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my small world of analytics! 
  Or, you can call it a business analytic case playground!
  <br><br>
  I wish someday I could become
  a creative,experienced marketing professional!  
  
  Let's study hard and play hard! 
  <a href="https://www.linkedin.com/in/yunjiaoliu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: 44184752 # your Google Analytics tracking ID here
