'title: Yunjiao Liu # your name (or website title) here
logo: "/images/IMG45 copy.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my small world of analytics! 
  Or, you can call it a case playground!
  <br><br>
  My goal is be a creative,experienced 
  marketing professional in the future!  
  <br><br>
  <a href="https://www.linkedin.com/in/yunjiaoliu/">
  View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-4418475-2 # your Google Analytics tracking ID here
