title: Yunjiao Liu # your name (or website title) here
logo: "/images/IMG45.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to the world of analytics! I would like to discribe this website as a analytics case playground!
  <br><br>
  Second description 
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
