title: Yunjiao Liu # your name (or website title) here
logo: "/images/photo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my small world of analytics! 
  Or, you can call it a case playground!
  <br><br>
  Let's study hard and play hard! 
  And become a creative,experienced marketing professional in the future!  
  
  <a href="https://www.linkedin.com/in/yunjiaoliu/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-4418475-2 # your Google Analytics tracking ID here
